# Generated by Django 4.2.3 on 2023-08-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer_service',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Email'),
        ),
    ]
