# Generated by Django 4.2.3 on 2023-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_customer_service_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
