# Generated by Django 4.2.3 on 2023-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_customer_service_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_service',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
