# Generated by Django 4.2.3 on 2023-08-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_customer_service_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_service',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
