# Generated by Django 4.2.3 on 2023-08-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_customer_service_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_service',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer_service',
            name='user_permissions',
        ),
    ]
