# Generated by Django 4.2.3 on 2023-08-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_customer_service_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_service',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='customer_service',
            name='refresh_token',
        ),
    ]
