# Generated by Django 4.2.3 on 2023-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_settings_client_delete_customer_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_logs',
            name='mail_server_response',
            field=models.TextField(max_length=100, verbose_name='Ответ почтового сервера'),
        ),
    ]
