# Generated by Django 4.2.3 on 2023-10-08 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_mailing_logs_mail_server_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('mailing_time_date',), 'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='mailing_time',
        ),
        migrations.AddField(
            model_name='settings',
            name='mailing_time_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время рассылки'),
            preserve_default=False,
        ),
    ]
